CREATE DATABASE AWS_PROJECT_DB;

CREATE TABLE AWS_PROJECT_USERS_TABLE (
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR(128)
);

INSERT INTO AWS_PROJECT_USERS_TABLE VALUES (1, "Dmytro");
INSERT INTO AWS_PROJECT_USERS_TABLE VALUES (1, "Alex");

SELECT * FROM AWS_PROJECT_USERS_TABLE;